### ISSUE TITLE
a problem about memory

### ISSUE THREAD

**Issue by wentaoxandry** [georgesterpu/pyVSR#2]
Hello @georgesterpu ,

I'm trying use your code generate aam features, but I have a problem with memory, 

every time when I run example_aam.py, I have this error:OSError: [Errno 12] Cannot allocate memory, I have see each time, there are many ffmpeg progress running at the same time, then this error will come. 
python shows the error come from this step:
     frame_buffer += frames
            if len(frame_buffer) > buffer_len:
                # 2. retrain AAM
                aam.increment(frame_buffer,
                              group=self._landmarkGroup,
                              shape_forgetting_factor=1.0,
                              appearance_forgetting_factor=1.0,
                              verbose=False,
                              batch_size=None)

I want to ask if there is any way to fix this problem, and still run the program?

Thank you so much

**Comment by wentaoxandry** [comment]
have solved:) thank you

**Comment by georgesterpu** [comment]
Great. If you are willing to, please add a few explanations for other people who are likely to encounter the same problem in the future.

I do remember having some high memory usage at some point with the AAM code, however with 64GB of RAM I could train the AAM just fine. [Our article](https://avsp2017.loria.fr/wp-content/uploads/2017/07/AVSP2017_paper_17.pdf) using pyVSR explains how we sampled from the video frames. This repository is no longer actively mantained, so I would recommend directly reaching to the developers of **menpo** on their discussion group.

**Comment by wentaoxandry** [comment]
what I have done is reduce buffer_len, until the program can right running.
