### ISSUE TITLE
OuluVS2 dataset

### ISSUE THREAD

**Issue by jeonsanghun** [georgesterpu/pyVSR#5]
Hello, friend.

I want to use the OuluVS2 dataset, but I don't think the homepage is operating anymore.

So if you don't mind, can you share me the OuluVS2 dataset?

jeon7887@gmail.com

**Comment by georgesterpu** [comment]
Hi @jeonsanghun 
Sorry to hear that the OuluVS2 webpage is not currently available.
I am not affiliated with the University of Oulu and do not own any rights to store or redistribute that dataset.
My best advice would be to send an inquiry to the authors over an official channel.

**Comment by jeonsanghun** [comment]
> Hi @jeonsanghun
> Sorry to hear that the OuluVS2 webpage is not currently available.
> I am not affiliated with the University of Oulu and do not own any rights to store or redistribute that dataset.
> My best advice would be to send an inquiry to the authors over an official channel.

We're going to do a simple test, too, but is it impossible to share it?
